server:
  servlet:
    encoding:
      force-response: true
      
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: application-secret.yml
